"""initial_schema

Revision ID: fce17478b81d
Revises: 
Create Date: 2026-06-23 15:30:04.219534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce17478b81d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('crawl_runs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('time_window_start', sa.DateTime(), nullable=True),
    sa.Column('time_window_end', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('crawl_run_id', sa.String(length=12), nullable=False),
    sa.Column('citation_coverage', sa.Float(), nullable=False),
    sa.Column('unsupported_claim_rate', sa.Float(), nullable=False),
    sa.Column('dedup_rate', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('token_cost_usd', sa.Float(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_crawl_run_id'), 'eval_runs', ['crawl_run_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('crawl_run_id', sa.String(length=12), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('markdown_path', sa.String(length=1024), nullable=True),
    sa.Column('json_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_company_id'), 'reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_reports_crawl_run_id'), 'reports', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('crawl_run_id', sa.String(length=12), nullable=False),
    sa.Column('company_id', sa.String(length=12), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('supporting_event_ids_json', sa.Text(), nullable=False),
    sa.Column('supporting_document_ids_json', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_crawl_run_id'), 'signals', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company_id', sa.String(length=12), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_company_id'), 'sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('report_id', sa.String(length=12), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('supporting_citation_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_report_id'), 'claims', ['report_id'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('crawl_run_id', sa.String(length=12), nullable=False),
    sa.Column('source_id', sa.String(length=12), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('raw_html_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_text_path', sa.String(length=1024), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_documents_checksum'), 'raw_documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_raw_documents_crawl_run_id'), 'raw_documents', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_id'), 'raw_documents', ['source_id'], unique=False)
    op.create_table('normalized_documents',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('raw_document_id', sa.String(length=12), nullable=False),
    sa.Column('company_id', sa.String(length=12), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('dedup_group', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_documents_company_id'), 'normalized_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_normalized_documents_content_hash'), 'normalized_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_normalized_documents_dedup_group'), 'normalized_documents', ['dedup_group'], unique=False)
    op.create_index(op.f('ix_normalized_documents_published_at'), 'normalized_documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_normalized_documents_raw_document_id'), 'normalized_documents', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_normalized_documents_source_type'), 'normalized_documents', ['source_type'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('report_id', sa.String(length=12), nullable=False),
    sa.Column('claim_id', sa.String(length=12), nullable=True),
    sa.Column('document_id', sa.String(length=12), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['normalized_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_claim_id'), 'citations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.create_index(op.f('ix_citations_report_id'), 'citations', ['report_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('document_id', sa.String(length=12), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['normalized_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_embedding_id'), 'document_chunks', ['embedding_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('document_id', sa.String(length=12), nullable=False),
    sa.Column('company_id', sa.String(length=12), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['normalized_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_company_id'), 'events', ['company_id'], unique=False)
    op.create_index(op.f('ix_events_document_id'), 'events', ['document_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_published_at'), 'events', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_published_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_document_id'), table_name='events')
    op.drop_index(op.f('ix_events_company_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_document_chunks_embedding_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_citations_report_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_claim_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_normalized_documents_source_type'), table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_raw_document_id'), table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_published_at'), table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_dedup_group'), table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_content_hash'), table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_company_id'), table_name='normalized_documents')
    op.drop_table('normalized_documents')
    op.drop_index(op.f('ix_raw_documents_source_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_crawl_run_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_checksum'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_claims_report_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_company_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_crawl_run_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_crawl_run_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_company_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_eval_runs_crawl_run_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
